name       : perl-io-utf8-strict
version    : 0.007
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/L/LE/LEONT/PerlIO-utf8_strict-0.007.tar.gz : 83a33f2fe046cb3ad6afc80790635a423e2c7c6854afacc6998cd46951cc81cb
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : PerlIO::utf8_strict - Fast and correct UTF-8 IO
description: |
    PerlIO::utf8_strict - Fast and correct UTF-8 IO
builddeps  :
     - perl-test-exception
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
